---
name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Generate matrix
        id: generate-matrix
        uses: wandnz/action-supported-distro-releases@v1

  molecule:
    name: Molecule (ansible:${{ matrix.ansible }}, ${{ matrix.target }})
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.target }}
    needs: generate-matrix
    strategy:
      matrix:
        target: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
        ansible:
          - "2.10"
          - "latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Setup python
        run: |
          apt update
          apt -y install python3 python3-pip python3-venv
      - name: Setup ansible
        shell: bash
        run: |
          python3 -m venv /venv
          if [ "${{ matrix.ansible }}" == "latest" ]; then
            /venv/bin/pip3 install ansible
          else
            /venv/bin/pip3 install ansible~=${{ matrix.ansible }}
          fi
      - name: Setup ansible problem matchers
        uses: wandansible/action-ansible-problem-matchers@v1
      - name: Install test dependencies
        run: /venv/bin/pip3 install -r test-requirements.txt
      - name: Run molecule
        shell: bash
        run: |
          source /venv/bin/activate
          molecule test
        env:
          MOLECULE_DOCKER_IMAGE: ${{ matrix.target }}
